version: "3.9"
services:
    family:
      build: ./FamilyApp
      ports:
        - "3030:3030"
      depends_on:
        - database
      restart: on-failure
    member:
      build: ./FamilyMemberApp
      ports:
        - "10101:10101"
      depends_on:
        - database
#        - family
      restart: on-failure
    database:
      container_name: 'mysql'
      image: mysql:8.0
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
#        MYSQL_USER: root
        MYSQL_DATABASE: db
      ports:
          - "3306:3306"